# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Feature-Family-Based Reliability Analysis of Software Product Lines
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
   This work is being developed in a jointly effort of researchers of the
   following universities
   <img src="http://andrelanna.github.io/journal-submission/assets/unb.jpg"><br/>
   <img src="http://andrelanna.github.io/journal-submission/assets/unamur.jpg"><br/>
   <img src="http://andrelanna.github.io/journal-submission/assets/passau.jpg"><br/>

baseurl: "/journal-submission" # #the subpath of your site, e.g. /blog
url: "https://andrelanna.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
